Server:
  Name: 'Im-Services'
  Host: "localhost"
  ListenPort: 9000
  Node: "http://localhost:9000"
  CoroutinePoll: 100000 # 启动的协程池数量
  GrpcListen: ':9001' # grpc端口
  FilePath: "./asserts/UploadFile"
  ClusterOpen: false
MySQL:
  Host: "127.0.0.1"
  Port: 3306
  Database: "grtcm"
  Username: "root"
  Password: "@aoweichen"
  Charset: "utf8mb4"
Redis:
  host: '127.0.0.1'
  port: 6379
  password:
  db: 1
  poll: 15 #连接池 默认为4倍cpu数
  conn: 10 #最小空闲连接数
Logger:
  Level: 'debug' # 开发时推荐使用 "debug" 或者 "info" ，生产环境下使用 "error"
  Type: 'daily' #"single" 独立的文件  "daily" 按照日期每日一个
  LogFilePath: './logs/logs.log'
  MaxSize: 64 # 保存最大单位 M
  MaxBackup: 30 #最多保存日志文件数，0 为不限，MaxAge 到了还是会删
  MaxAge: 7 #最多保存多少天
  Compress: false #是否压缩

Nsq:
  LookupHost: '127.0.0.1:4161'
  NsqHost: '127.0.0.1:4150'

Consul:
  Host: "localhost"
  Port: ":8500"

QiNiu:
  accessKey: 'hx8_OcNEZOJ_AUx4gi74mX_kweJ1XNjKz8dRR7z9'
  secretKey: 'af3aCLEdby1FRyF460aY8H-pfdvDqiwrpqyGy1NK'
  bucket: 'grtc'
  domain: 's08krditv.hn-bkt.clouddn.com'
